export const article: string;
export const points: string;
export const info: string;
export const animated: string;
export const placeHolderShimmer: string;
export const animatedPrimary: string;
export const animatedSecondary: string;
export const primaryShell: string;
export const container: string;
